Add consult integration
nex3/perspective-el pull request #176
Opened 2022-03-06 19:19 UTC by ivan-pop

This adds new variable `persp-consult-source` which is source that can be used
with `consult-buffer-sources` and instruction to README on how to use it

2022-03-07 15:20 UTC, gcv requested changes
Thanks! Just a couple of nitpicks before merging.

2022-03-07 15:20 UTC, gcv commented on README.md
> +(add-to-list consult-buffer-sources persp-consult-source)
`add-to-list` takes a symbol, so that should be `(add-to-list 'consult-buffer-sources persp-consult-source)`.

2022-03-07 15:20 UTC, gcv commented on README.md
> +list of all buffers by filtering with `b` key. Example configuration:
How do I filter with <kbd>b</kbd>? For me, that just filters to buffers containing the letter `b`. (I do use Consult, but I'm not an expert.)

2022-03-08 11:59 UTC, ivan-pop commented
@gcv Just pushed fixes. Regarding `consult--buffer-state` it is defined in consult using `consult--define-state` macro

2022-03-08 12:33 UTC, ivan-pop commented
Should i maybe wrap config part in README in `with-eval-after-load` too?

2022-03-09 01:48 UTC, gcv commented
> Should i wrap config part in README in `with-eval-after-load` too?

I don’t know. Part of me thinks it’ll be nicer and more user-friendly to do it, but that kind of automatic setup seems counter to the “let the user decide” spirit of Vertico and Consult. Feel free to do whichever you think is right and I’ll merge it.

2022-03-09 10:39 UTC, ivan-pop commented
I agree that it is better to let user decide it, lets go without it

2022-03-13 07:21 UTC, merged

2022-03-13 07:22 UTC, gcv commented
Merged. Thank you for contributing to Perspective!